### ISSUE TITLE
Support Tracing Web Sites

### ISSUE THREAD

**Issue by walles** [GoogleCloudPlatform/opentelemetry-operations-js#114]
# Request
Currently, the exporter in this repo is only documented for running in Node.js.

Kindly add documentation for how to run it in a browser, on publicly accessible web pages as well.

# Background
I have a web page instrumented with Google Analytics.

I would like that web page to report Cloud Trace information so that tracing information shows up at <https://console.cloud.google.com/traces>.

I also have a backend service already reporting tracing information into the above URL.

I would like for my web page traces and the (Java) backend traces to be connected in the trace visualisation at the above URL.

**Comment by reggiemcdonald** [comment]
Hi @walles 

This exporter is for node only.

Tracing at the client side can be seen in this [example](https://cloud.google.com/community/tutorials/web-instrumentation)

**Comment by mbrevda** [comment]
@reggiemcdonald  is there no way to send traces directly to Cloud Trace from the front end _without_ requiring my own server?

**Comment by aabmass** [comment]
@mbrevda no this is not possible. You have to run an OpenTelemetry collector to do this.

**Comment by mbrevda** [comment]
With the advent of serverless, this requirement seems arbitrary and counterintuitive. Are there any plans to expose an endpoint where front-end traces can be sent directly to Cloud Trace?

**Comment by aabmass** [comment]
Thanks for the feedback @mbrevda. We are having discussions to see how we can support this, but there are a few issues
- How can a frontend client authenticate requests to Cloud Trace if using this exporter directly? You'd have to give them an auth token to make requests to Cloud Trace API, which is a security issue.
- You can use the OTLP exporter as mentioned above and point it at a serverless endpoint that forwards requests to an OpenTelemetry Collector. The problem is running the Collector serverless (Cloud Run) because it does background processing. We haven't tested this, but it could work :)

**Comment by mbrevda** [comment]
> How can a frontend client authenticate requests to Cloud Trace if using this exporter directly

Most other offerings provide a key/identifier used to uniquely the hosting app. This applies to the web, but equally to mobile apps where the auth token cannot be properly protected. While this is obviously not the most secure setup, considering that the key provides write-only abilities of data (no settings can be changed with this key) the risks are pretty minimal. One example of this is Google Analytics. 

> The problem is running the Collector serverless

The larger issue is that the serverless paradigm is generally preferred by those looking to host less, not more, of their own infrastructure. Of course, a serverless endpoint _could_ work here, but it seems like an unnecessary hurdle considering that Trace is anyway hosting endpoints for this very purpose.
