### ISSUE TITLE
Add support for Histogram

### ISSUE THREAD

**Issue by TigerHe7** [GoogleCloudPlatform/opentelemetry-operations-js#129]
**Change Requested:**
Add support for `OTMetricKind.ValueRecorder` from OpenTelemetry SDK.

**Current Behavior:**
Currently, trying to export metrics collected via `ValueRecorder` results in an error from Google Cloud Monitoring regarding the `MetricKind.UNSPECIFIED` being used.

**Comment by aabmass** [comment]
The OTel metrics specification still hasn't decided what default aggregator will be used for ValueRecorder. It's looking like it will be "some histogram sketch" (e.g. DDSketch) which will produce fancy histograms. Since this will be changing, we should put this work off until the JS SDK is up to date.

**Comment by jonnydgreen** [comment]
Looking at the spec feature freeze milestone, this is due by the end of September 2021: https://github.com/open-telemetry/opentelemetry-specification/milestone/14. If you need, happy to help you both out on an implementation when the default aggregator has been chosen for ValueRecorder and the JS SDK is up to date :)

**Comment by aabmass** [comment]
We're always happy to receive PRs 😃  I think this is completely blocked until this work is done in the spec (September timeline) AND its implemented in the JS SDK (maybe later).
