### ISSUE TITLE
documentation request: example of adding trace and spanId properties to log for Cloud Logging

### ISSUE THREAD

**Issue by naseemkullah** [GoogleCloudPlatform/opentelemetry-operations-js#153]
Please see https://cloud.google.com/trace/docs/trace-log-integration

**Comment by naseemkullah** [comment]
In particular I'd like to know the best practice on fetching the project Id for a workload running in GCP since the trace value needs to be:

```
   projects/[PROJECT_ID]/traces/[TRACE_ID]
```

I've avoided added PROJECT_ID or equivalent as an env var for workloads, and would preferably continue to.

Also looked at https://github.com/googleapis/gcp-metadata#access-specific-properties which seems a little involved.

Any suggestions? @kintel @steren @jonahrosenblum

**Comment by kintel** [comment]
I think the best way to obtain the Project ID is likely asking GoogleAuth: https://github.com/googleapis/google-auth-library-nodejs#choosing-the-correct-credential-type-automatically. Google auth also have a bunch of internal ways of obtaining the Project ID from common env. variables etc.

However, since this exporter already does the job of determining the correct Project ID (https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/ddf130b425733ad806f95e970066833de3f17780/packages/opentelemetry-cloud-trace-exporter/src/trace.ts#L52), we may want to expose that as a public API here. As adding a public API would be something we need to consider across all languages, that's unlikely to happen very soon.

@aabmass Is this something you could look into, perhaps by zooming out a bit and thinking about how to write logs with correct Trace info from a OpenTelemetry-instrumented app?

**Comment by aabmass** [comment]
I think it would be easy to update our documentation here showing how to get the project ID and trace ID. We should also explore linking to integrations with Cloud Logging SDK and OTel Logging SDK which is actively being worked on.

**Comment by aabmass** [comment]
Triaged again. We'd like to provide and document a better story for correlating traces and logs. Raised to p2

**Comment by dashpole** [comment]
Still relevant, and something we plan to tackle.

**Comment by aabmass** [comment]
This is well documented on the Google Cloud documentation page now: https://cloud.google.com/stackdriver/docs/instrumentation/setup/nodejs#config-structured-logging

This example is for Pino but the approach would be similar for other logging frameworks.

> In particular I'd like to know the best practice on fetching the project Id for a workload running in GCP since the trace value needs to be:
> 
> ```
>    projects/[PROJECT_ID]/traces/[TRACE_ID]
> ```

This requirement has been removed if you're logging to stdout/stderr in a managed environment like GKE, Cloud Run, GCE with Ops Agent etc. You can just log the trace ID directly.
