### ISSUE TITLE
Update resource detection mapping to be compliant with metric exporter spec

### ISSUE THREAD

**Issue by psx95** [GoogleCloudPlatform/opentelemetry-operations-js#553]
For MR types `cloud_run_revision` and `cloud_function`, the metric exporter spec currently falls back to either `generic_task` or `generic_node`. 

This is currently being violated [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/main/packages/opentelemetry-resource-util/src/index.ts#L122). These explicit mappings need to be removed in order to be compliant with the spec.

**Comment by aabmass** [comment]
After taking another look at the code, I believe we have the same behavior as Java already for the metrics exporter. It uses generic_task/generic_node for Cloud Run and Cloud Functions because `includeUnsupportedResources` is false

here https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/db2664c0fc1ff1193d539263ae6197502c5948cb/packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts#L145-L147

https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/db2664c0fc1ff1193d539263ae6197502c5948cb/packages/opentelemetry-resource-util/src/index.ts#L226

Does that sound good @psx95?

----

However, for the Trace exporter we still send the old monitored resource as span labels (`g.co/r/cloud_run_revision/...` labels). I think we decided to no longer do that. I will send a PR to stop doing that.

**Comment by psx95** [comment]
I see, I did not notice the flag variable.

It is fine in that case.

**Comment by aabmass** [comment]
Thanks, I will send a PR in any event to stop sending `cloud_run_revision` and `cloud_function` unsupported MRs for the trace exporter, so this is in line with what Java and Go do.
